version: '3'
services:
  db:
    container_name: pg_db
    image: postgres
    restart: always
    env_file:
      - ./db.env
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgdmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./pgadmin.env
    ports:
      - 8080:80
    depends_on:
      - db

  back:
    image: back:latest
    container_name: back
    restart: always
    volumes:
      - static_data:/app/static
    build:
      context: ./multi_fin_bot/back/
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_data:/var/www/html/static
      - ./multi_fin_bot/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - back

  telegram:
    image: telegram:latest
    container_name: telegram
    restart: always
    build:
      context: ./multi_fin_bot/telegram/
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - back

  celery-worker:
    image: celery:worker
    container_name: celery-worker
    restart: always
    build:
      context: ./multi_fin_bot/back/
      dockerfile: Dockerfile
    command: celery -A proj worker -l INFO
    depends_on:
      - back
      - redis

  celery-beat:
    image: celery:beat
    container_name: celery-beat
    restart: always
    build:
      context: ./multi_fin_bot/back/
      dockerfile: Dockerfile
    command: celery -A proj beat -l info
    depends_on:
      - back
      - redis

  redis:
    image: redis:5-alpine
    container_name: redis
    restart: always

volumes:
  static_data:
