version: '3.11'

services:
  back:
    image: back:latest
    container_name: back
    volumes:
      - .:/app
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
