# Generated by Django 4.1.7 on 2023-04-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_categoryincome_categoryexpense_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryincome',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_currency',
        ),
        migrations.DeleteModel(
            name='CategoryExpense',
        ),
        migrations.DeleteModel(
            name='CategoryIncome',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
