# Generated by Django 4.1.7 on 2023-05-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bot.currency', verbose_name='Base currency'),
            preserve_default=False,
        ),
    ]
