# Generated by Django 4.1.7 on 2023-05-09 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0014_categoryincome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryincome',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.categoryincome')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
